[build]
  base = "skillcef"  # The folder containing the app.py and Netlify config
  publish = "skillcef"  # Directory to serve files from (typically static or public folder)
  functions = "skillcef"  # If you're using Python serverless functions

[[plugins]]
  package = "@netlify/plugin-python"
